site_name: Práctica 4 Pedro Díaz Fornet
site_url: https://pdfornet.github.io/Practica_4/
docs_dir: 'md'
site_dir: 'docs'
repo_url: https://github.com/PDFornet/Practica_4.git 
repo_name: PDFornet/Practica_4

theme:
    name: mkdocs
    include_search_page: false
    font:
        code: Verdana
        text: Calibri
    palette: 
      scheme: default
      primary: teal
      accent: green
    favicon: images/apache.png
    features:
        #- header.autohide
        - toc.follow
        - toc.integrate
        - search.suggest

nav:
    - índex: index.md
    - Markdown: markdown.md
    - Python: python.md


extra:
    generator: false #Muestra en el pie de página que se ha realizado con Mkdocs
    social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<email-address>
